[project]
name        = "django-static-mathjax"
version     = "3.2.2.0"
description = "JavaScript library for displaying mathematics on the Web"
readme      = "README.md"

[build-system]
requires      = ["setuptools >= 61"]
build-backend = "setuptools.build_meta"
